### ISSUE TITLE
Lista farmaci da ricerca e Disponibilità

### ISSUE THREAD

**Issue by feddynventor** [FLopriore/pharmate#1]
Se si espande un preciso prodotto, escono comunque tutte le farmacie, anche se per quel prodotto non c'è effettiva disponibilità.
Se si procede con l'ordine, non viene segnalato alcun errore, nessun dialog.
Sembra che l'unico dialog sia "ordine confermato"

**Comment by FLopriore** [comment]
Bug fixed in this [commit](https://github.com/FLopriore/pharmate/commit/44ad55230e77072522d065450491e950e48c5ab6).

**Comment by FLopriore** [comment]
Bug fixed in this [commit](https://github.com/FLopriore/pharmate/commit/44ad55230e77072522d065450491e950e48c5ab6).
