### ISSUE TITLE
Layout overflow

### ISSUE THREAD

**Issue by feddynventor** [FLopriore/pharmate#2]
Schermata conferma ordine ha problemi di overflow. Il tasto si può comunque cliccare

![Screenshot_20231222-155529_pharmate](https://github.com/FLopriore/pharmate/assets/62469018/a0913b58-f637-4236-88ac-036387b3b006)

**Comment by FLopriore** [comment]
Fixed in this [commit](https://github.com/FLopriore/pharmate/commit/1390b41af4c9911d4783ff6b22fe9c5e6d1cdcbc).
