### ISSUE TITLE
Font troppo piccolo

### ISSUE THREAD

**Issue by feddynventor** [FLopriore/pharmate#3]
Ritengo sia da sistemare ai fini degli screenshot nel report e eventuale demo hands-on

Inibire overflow con i 3 puntini (il testo tagliato è troppo corto)

![Screenshot_20231222-155541_pharmate](https://github.com/FLopriore/pharmate/assets/62469018/309dca44-ebbb-43e8-a349-7449df015349)

**Comment by FLopriore** [comment]
Fixed with this [commit](https://github.com/FLopriore/pharmate/commit/bff0975aeb4b953b9824eb52772a814cda9758d0).
